name: classifier
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install requirements
          pip install -r requirements.txt
          python classifier.py
          python csv_to_markdown.py metrics.csv --delimiter , --hasHeader

          # Write your CML report
          echo "## Metrics" >> report.md
          cat metrics.txt >> report.md
          echo "## Confusion matrix" >> report.md
          cml-publish confusion_matrix.png --md >> report.md
          cml-send-comment report.md